"""Added lecturer

Revision ID: 9d1f131c20b2
Revises: 89fba7e59073
Create Date: 2021-11-03 15:21:39.617965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d1f131c20b2'
down_revision = '89fba7e59073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture', sa.Column('lecturer', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecture', 'lecturer')
    # ### end Alembic commands ###
