"""Added lecturer

Revision ID: e6874bfcf7e7
Revises: 9d1f131c20b2
Create Date: 2021-11-03 15:29:17.896945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6874bfcf7e7'
down_revision = '9d1f131c20b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture', sa.Column('day', sa.String(length=64), nullable=True))
    op.drop_column('lecture', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture', sa.Column('date', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('lecture', 'day')
    # ### end Alembic commands ###
